// @ts-check
import { defineConfig } from "astro/config";

/**
 * Single source of truth for where this site is deployed.
 *
 * T2-102 finished MIG-01/MIG-02: hosting is Vercel, the site is served from
 * the apex of monterogarage.com, so there is no deploy path any more and
 * `base` is `/`. The GitHub Pages era (`https://sandgraal.github.io` +
 * `base: "/monterogarage"`, a Pages *project site* served under `/<RepoName>/`)
 * ended with it, and so did CI's "base must equal /<RepoName>" assertion —
 * that was a GitHub-Pages-project-site rule and nothing else.
 *
 * `site` names the production origin, not whichever origin a given build is
 * served from. Vercel preview deployments therefore emit canonical/hreflang
 * URLs on monterogarage.com rather than on the preview's own `*.vercel.app`
 * host — which is what you want: a preview must never invite a crawler to
 * index it, and previews are `noindex` on Vercel regardless.
 *
 * Both values are changed here and nowhere else: every internal link,
 * canonical URL and hreflang href is derived from them through
 * `src/i18n/routing.ts` (`import.meta.env.BASE_URL`) and `Astro.site`.
 */
export default defineConfig({
  site: "https://monterogarage.com",
  base: "/",

  // Static output (SCF-01).
  output: "static",

  // I18N-01: both locales are prefixed, so neither is privileged — `/en/…`
  // and `/es/…` are generated by the same routes from the same code.
  // I18N-02: `redirectToDefaultLocale` is off because `src/pages/index.astro`
  // owns `/` and negotiates the locale instead of hard-redirecting to `/en/`.
  i18n: {
    locales: ["en", "es"],
    defaultLocale: "en",
    routing: {
      prefixDefaultLocale: true,
      redirectToDefaultLocale: false,
    },
  },
});
