// @ts-check
import { defineConfig } from "astro/config";

/**
 * Single source of truth for where this site is deployed.
 *
 * Today: GitHub Pages project pages — https://sandgraal.github.io/Gitana-Montero/
 * (owner decision, 2026-08-27). If it later moves to a custom domain, change
 * `site` and set `base` to "/" here and nowhere else: every internal link,
 * canonical URL and hreflang href is derived from these two values through
 * `src/i18n/routing.ts` (`import.meta.env.BASE_URL`) and `Astro.site`.
 */
export default defineConfig({
  site: "https://sandgraal.github.io",
  base: "/Gitana-Montero",

  // Static output (SCF-01).
  output: "static",

  // I18N-01: both locales are prefixed, so neither is privileged — `/en/…`
  // and `/es/…` are generated by the same routes from the same code.
  // I18N-02: `redirectToDefaultLocale` is off because `src/pages/index.astro`
  // owns `/` and negotiates the locale instead of hard-redirecting to `/en/`.
  i18n: {
    locales: ["en", "es"],
    defaultLocale: "en",
    routing: {
      prefixDefaultLocale: true,
      redirectToDefaultLocale: false,
    },
  },
});
